config/routes.rb
ScoutifyDatabase::Application.routes.draw do

	get "welcome/index"

	resources :users
	resources :teams
	resources :games do
		get "tba_update", on: :member
		resources :events, only: [:index]
	end
	resources :events do
		get "tba_update", on: :member
		resources :matches, only: [:index]
	end
	resources :matches, except: :index do
		get "tba_update", on: :member
		resources :records, only: [:index]
	end
	resources :records, except: :index

	root 'welcome#index'

	

end

app/models/record.rb
class Record < ActiveRecord::Base
	serialize :data

	belongs_to :match
	belongs_to :team
	belongs_to :user
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	before_action :set_record, only: [:show, :edit, :update, :destroy]

	# GET /records
	# GET /records.json
	def index
		@records = params[:match_id] ? Record.where(match_id: params[:match_id]): Record.all
	end

	# GET /records/1
	# GET /records/1.json
	def show
	end

	# GET /records/new
	def new
		@record = Record.new
	end

	# GET /records/1/edit
	def edit
	end

	# POST /records
	# POST /records.json
	def create
		@record = Record.new(record_params)

		respond_to do |format|
			if @record.save
				format.html { redirect_to @record, notice: 'Record was successfully created.' }
				format.json { render action: 'show', status: :created, location: @record }
			else
				format.html { render action: 'new' }
				format.json { render json: @record.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /records/1
	# PATCH/PUT /records/1.json
	def update
		respond_to do |format|
			if @record.update(record_params)
				format.html { redirect_to @record, notice: 'Record was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @record.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /records/1
	# DELETE /records/1.json
	def destroy
		@record.destroy
		respond_to do |format|
			format.html { redirect_to records_url }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_record
		@record = Record.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def record_params
		params.require(:record).permit(:data, :team_id, :event_id, :user_id)
	end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_area :data %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.number_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Match</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.team ? record.team.name : record.team_id %></td>
        <td><%= record.match ? record.match.number : record.match_id %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @record.data %>
</p>

<p>
  <strong>Team:</strong>
  <%= @record.team ? link_to @record.team.name, @record.team : @record.team_id %>
</p>

<p>
  <strong>Match:</strong>
  <%= @record.match ? link_to @record.match.number, @record.match : @record.match_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @record.user_id %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>