config/routes.rb
ScoutifyDatabase::Application.routes.draw do

	get "welcome/index"

	resources :users
	resources :teams
	resources :games do
		get "tba_update", on: :member
		resources :events, only: [:index]
	end
	resources :events do
		get "tba_update", on: :member
		resources :matches, only: [:index]
	end
	resources :matches, except: :index do
		get "tba_update", on: :member
		resources :records, only: [:index]
	end
	resources :records, except: :index

	root 'welcome#index'

	

end

app/models/event.rb
class Event < ActiveRecord::Base
	require "net/http"
	include TBA

	belongs_to :game
	has_many :matches
	has_many :records, through: :matches
	has_and_belongs_to_many :teams

	def tba_update(key)
		res = tba_request :event, key

		tba_error(res.uri, res.code, res.body) unless res.is_a?(Net::HTTPSuccess)

		json = MultiJson.load(res.body)

		self.name = json["name"]
		self.game = Game.where(year: json["year"]).first
		self.game ||= Game.create(year: json["year"])
		self.save

		unless json["teams"].empty?
			teams_res = tba_request :teams, json["teams"].join(",")

			tba_error(teams_res.uri, teams_res.code, teams_res.body) unless teams_res.is_a?(Net::HTTPSuccess)

			teams_json = MultiJson.load teams_res.body

			json["teams"].each do |team_key|
				team_number = (teams_json.detect { |t| t["key"] == team_key })["team_number"]
				team = Team.where(number: team_number).first

				unless team
					team = Team.create
					team.tba_update team_key
				end

				self.teams << team unless self.teams.include? team
			end

			unless json["matches"].empty?
				matches_csv = json["matches"][0]
				matches_json = []
				json["matches"].drop(1).each do |match_key|
					if (TBA_BASE_URL +
					    TBA_REQUEST_TYPE_TABLE[:matches] +
					    Rack::Utils.escape(matches_csv) +
					    "%2C" +
					    match_key).length > 2000

						matches_res = tba_request :matches, matches_csv
						tba_error(matches_res.uri, matches_res.code, matches_res.body) unless matches_res.is_a?(Net::HTTPSuccess)
						matches_json += MultiJson.load matches_res.body
						matches_csv = ""
					else
						matches_csv += ","
					end
					matches_csv += match_key
				end

				matches_res = tba_request :matches, matches_csv
				tba_error(matches_res.uri, matches_res.code, matches_res.body) unless matches_res.is_a?(Net::HTTPSuccess)
				matches_json += MultiJson.load matches_res.body

				json["matches"].each do |match_key|
					match = self.matches.where(number: match_key.split("_")[1]).first
					match ||= Match.create(event_id: id)

					match.tba_update(match_key, teams_json, matches_json)
				end
			end
		end
		self
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, only: [:show, :edit, :update, :destroy]

	# GET /events
	# GET /events.json
	def index
		@events = params[:game_id] ? Event.where(game_id: params[:game_id]): Event.all
	end

	# GET /events/1
	# GET /events/1.json
	def show
	end

	# GET /events/new
	def new
		@event = Event.new
	end

	# GET /events/1/edit
	def edit
	end

	# POST /events
	# POST /events.json
	def create
		@event = Event.new(event_params)

		respond_to do |format|
			if @event.save
				format.html { redirect_to @event, notice: 'Event was successfully created.' }
				format.json { render action: 'show', status: :created, location: @event }
			else
				format.html { render action: 'new' }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /events/1
	# PATCH/PUT /events/1.json
	def update
		respond_to do |format|
			if @event.update(event_params)
				format.html { redirect_to @event, notice: 'Event was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /events/1
	# DELETE /events/1.json
	def destroy
		@event.destroy
		respond_to do |format|
			format.html { redirect_to events_url }
			format.json { head :no_content }
		end
	end

	# GET /events/1/tba_update
	def tba_update
		call_rake :update_events, :event_id => params[:id].to_i
		redirect_to "/events/" + params[:id], notice: "Processing request. This could take quite a few minutes."
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_event
		@event = Event.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def event_params
		params.require(:event).permit(:name, :description, :game_id)
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Game:</strong>
  <%= @event.game_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>