config/routes.rb
ScoutifyDatabase::Application.routes.draw do

	get "welcome/index"

	resources :users
	resources :teams
	resources :games do
		get "tba_update", on: :member
		resources :events, only: [:index]
	end
	resources :events do
		get "tba_update", on: :member
		resources :matches, only: [:index]
	end
	resources :matches, except: :index do
		get "tba_update", on: :member
		resources :records, only: [:index]
	end
	resources :records, except: :index

	root 'welcome#index'

	

end

app/models/match.rb
class Match < ActiveRecord::Base
	require "net/http"
	include TBA

	has_many :records
	belongs_to :event

	def tba_update(key, teams_json = nil, matches_json = nil)
		unless matches_json
			res = tba_request :match, key

			tba_error(res.uri, res.code, res.body) unless res.is_a?(Net::HTTPSuccess)

			matches_json = MultiJson.load res.body
		end

		json = matches_json.detect{ |m| m["key"] == key }

		return nil unless json
		# this can happen if we think there is a third elim match in a group
		# during the first request, but there isn't during the second request
		return nil if json["alliances"]["red"]["score"] == -1 && json["alliances"]["blue"]["score"] == -1

		unless (red_score == json["alliances"]["red"]["score"] &&
		        blue_score == json["alliances"]["blue"]["score"] &&
		        number == json["key"].split("_")[1])

			self.red_score = json["alliances"]["red"]["score"]
			self.blue_score = json["alliances"]["blue"]["score"]
			self.number = json["key"].split("_")[1]
			self.save
		end

		unless teams_json
			teams_res = tba_request :teams, json["team_keys"].join(",")

			tba_error(teams_res.uri, teams_res.code, teams_res.body) unless teams_res.is_a?(Net::HTTPSuccess)

			teams_json = MultiJson.load teams_res.body
		end

		["red", "blue"].each do |team_color|
			position_base_num = (team_color == "red") ? 0 : 3

			json["alliances"][team_color]["teams"].map do |team_key|
				# Sometimes TBA uses team keys like "frc973B"; ignore these.
				if teams_json.detect { |t| t["key"] == team_key }
					team_number = (teams_json.detect { |t| t["key"] == team_key })["team_number"]
					team = Team.where(number: team_number).first

					unless team
						team = Team.create
						team.tba_update team_key
					end
				end

				query_string = "" # scope?

				if team_color == "red"
					query_string = "position < 3 AND team_id == ?"
				elsif team_color == "blue"
					query_string = "position >= 3 AND team_id == ?"
				end

				if records.where(query_string, (team && team.id)).empty?
					for i in position_base_num..(position_base_num + 2) do
						if records.where(position: i).empty?
							Record.create match_id: id, position: i, team_id: (team && team.id)
							break
						end
					end
				end
			end
		end
		self
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	before_action :set_match, only: [:show, :edit, :update, :destroy]

	# GET /matches
	# GET /matches.json
	def index
		@matches = params[:event_id] ? Match.where(event_id: params[:event_id]): Match.all
	end

	# GET /matches/1
	# GET /matches/1.json
	def show
	end

	# GET /matches/new
	def new
		@match = Match.new
	end

	# GET /matches/1/edit
	def edit
	end

	# POST /matches
	# POST /matches.json
	def create
		@match = Match.new(match_params)

		respond_to do |format|
			if @match.save
				format.html { redirect_to @match, notice: 'Match was successfully created.' }
				format.json { render action: 'show', status: :created, location: @match }
			else
				format.html { render action: 'new' }
				format.json { render json: @match.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /matches/1
	# PATCH/PUT /matches/1.json
	def update
		respond_to do |format|
			if @match.update(match_params)
				format.html { redirect_to @match, notice: 'Match was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @match.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /matches/1
	# DELETE /matches/1.json
	def destroy
		@match.destroy
		respond_to do |format|
			format.html { redirect_to matches_url }
			format.json { head :no_content }
		end
	end

	# GET /matches/1/tba_update
	def tba_update
		call_rake :update_match, :match_id => params[:id].to_i
		redirect_to "/matches/" + params[:id], notice: "Processing request."
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_match
		@match = Match.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def match_params
		params.require(:match).permit(:event_id, :match_number)
	end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :match_number %><br>
    <%= f.text_area :match_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Match number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.event.name %></td>
        <td><%= match.number %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @match.event_id %>
</p>

<p>
  <strong>Match number:</strong>
  <%= @match.number %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>