config/routes.rb
ScoutifyDatabase::Application.routes.draw do

	get "welcome/index"

	resources :users
	resources :teams
	resources :games do
		get "tba_update", on: :member
		resources :events, only: [:index]
	end
	resources :events do
		get "tba_update", on: :member
		resources :matches, only: [:index]
	end
	resources :matches, except: :index do
		get "tba_update", on: :member
		resources :records, only: [:index]
	end
	resources :records, except: :index

	root 'welcome#index'

	

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
		<%= csrf_meta_tags %>

		<title>Scoutify Database</title>

		<!-- Bootstrap core CSS -->
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

		<!-- Custom styles for this template -->
		
		<!-- Just for debugging purposes. Don't actually copy this line! -->
		<!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
		<%= navbar brand: "Scoutify Database", fixed: :top, responsive: true do %>
			<%= navbar_group do %>
				<%= navbar_item "Teams", teams_path %>
				<%= navbar_item "Games", games_path %>
				<%= navbar_item "Users", users_path %>
			<% end %>
			<% unless current_user %>
				<%= navbar_group align: "right" do %>
					<%= navbar_item "Sign Up", new_user_path %>
				<% end %>
			<% end %>
		<% end %>

		<div class="container">

			<div class="row row-offcanvas row-offcanvas-right">
				<div class="col-xs-12 col-sm-9">
					<%= yield %>
				</div><!--/span-->
				<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
					<div class="list-group">
						<a href="#" class="list-group-item active">Link</a>
						<a href="#" class="list-group-item">Link</a>
						<a href="#" class="list-group-item">Link</a>
						<a href="#" class="list-group-item">Link</a>
						<a href="#" class="list-group-item">Link</a>
						<a href="#" class="list-group-item">Link</a>
						<a href="#" class="list-group-item">Link</a>
						<a href="#" class="list-group-item">Link</a>
						<a href="#" class="list-group-item">Link</a>
						<a href="#" class="list-group-item">Link</a>
					</div>
				</div><!--/span-->
			</div><!--/row-->

			<!-- <hr> -->

			<!-- <footer> -->
			<!-- 	<p>&copy; Company 2013</p> -->
			<!-- </footer> -->
		</div><!--/.container-->

		<!-- Bootstrap core JavaScript
			 ================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>

</html>